#Data Cleaning Process

This is the python code to check null-values or duplicated in the 'Supply Chain Dataset'.

The dataset can be downloaded [here](https://docs.google.com/spreadsheets/d/1po7nlVs59W-nxm8coIKeOUsWYZI4h6X_xD_vR_uEcOI/edit?usp=sharing).

In [ ]:
import pandas as pd

##Import Data

In [ ]:
df = pd.read_csv("Supply Chain Dataset - DataCoSupplyChainDataset.csv")

In [ ]:
pd.set_option('display.max_columns', None)
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.750000,0.29,1,327.750000,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.750000,-0.80,1,327.750000,311.359985,-249.089996,South Asia,Rajast√°n,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.750000,-0.80,1,327.750000,309.720001,-247.779999,South Asia,Rajast√°n,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.750000,0.08,1,327.750000,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.750000,0.45,1,327.750000,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,EE. UU.,XXXXXXXXX,Maria,1005,Peterson,XXXXXXXXX,Home Office,NY,1322 Broad Glade,11207.0,7,Fan Shop,40.640930,-73.942711,Pacific Asia,Shangh√°i,China,1005,1/16/2016 3:40,26043,1004,0.000000,0.00,65177,399.980011,0.10,1,399.980011,399.980011,40.000000,Eastern Asia,Shangh√°i,CLOSED,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,EE. UU.,XXXXXXXXX,Ronald,9141,Clark,XXXXXXXXX,Corporate,CA,7330 Broad Apple Moor,93304.0,7,Fan Shop,35.362545,-119.018700,Pacific Asia,Hirakata,Jap√≥n,9141,1/16/2016 1:34,26037,1004,4.000000,0.01,65161,399.980011,-1.55,1,399.980011,395.980011,-613.770019,Eastern Asia,Osaka,COMPLETE,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,EE. UU.,XXXXXXXXX,John,291,Smith,XXXXXXXXX,Corporate,CT,97 Burning Landing,6010.0,7,Fan Shop,41.629959,-72.967155,Pacific Asia,Adelaide,Australia,291,1/15/2016 21:00,26024,1004,8.000000,0.02,65129,399.980011,0.36,1,399.980011,391.980011,141.110001,Oceania,Australia del Sur,PENDING,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Mary,2813,Smith,XXXXXXXXX,Consumer,PR,2585 Silent Autumn Landing,725.0,7,Fan Shop,18.213350,-66.370575,Pacific Asia,Adelaide,Australia,2813,1/15/2016 20:18,26022,1004,12.000000,0.03,65126,399.980011,0.48,1,399.980011,387.980011,186.229996,Oceania,Australia del Sur,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Andrea,7547,Ortega,XXXXXXXXX,Consumer,PR,697 Little Meadow,725.0,7,Fan Shop,18.290380,-66.370613,Pacific Asia,Nagercoil,India,7547,1/15/2016 18:54,26018,1004,16.000000,0.04,65113,399.980011,0.44,1,399.980011,383.980011,168.949997,South Asia,Tamil Nadu,PENDING_PAYMENT,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

##Checking Null Values

In [ ]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

Because `Product Description` and `Order Zipcode` columns have more than 75% null-values, it is recommended to drop the columns.

In [ ]:
df = df.drop(['Order Zipcode', 'Product Description'], axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Product Card Id                180519 non-null  int64
 44  Product Category Id            180519 non-null  int64
 45  Product Image                  180519 non-null  object
 46  Product Name                   180519 non-null  object
 47  Product Price                  180519 non-null  float64
 48  Product Status                 180519 non-null  int64
 49  shipping date (DateOrders)     180519 non-null  object
 50  Shipping Mode                  180519 non-null  object
dtypes: float64(13), int64(14), object(24)
memory usage: 70.2+ MB

There are 2 columns with some missing values, they are: `Customer Lname` and `Customer Zipcode`.

###Fill The Null-Values

In [ ]:
df[df['Customer Zipcode'].isnull()]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
35704,DEBIT,2,1,66.379997,189.660004,Late delivery,1,65,Consumer Electronics,CA,EE. UU.,XXXXXXXXX,Sara,14577,Foreman,XXXXXXXXX,Consumer,95758,Elk Grove,NaN,10,Technology,39.134159,-123.718552,Europe,Valence,Francia,14577,11/2/2017 18:31,71024,1352,63.220001,0.25,174339,252.880005,0.35,1,252.880005,189.660004,66.379997,Western Europe,Auvernia-R√≥dano-Alpes,COMPLETE,1352,65,http://images.acmesports.sports/Industrial+con...,Industrial consumer electronics,252.880005,0,11/4/2017 18:31,First Class
46440,PAYMENT,4,4,10.910000,38.959999,Shipping on time,0,75,Video Games,CA,EE. UU.,XXXXXXXXX,Eugenia,17171,Slater,XXXXXXXXX,Corporate,95758,Elk Grove,NaN,9,Discs Shop,38.408573,-121.449112,Pacific Asia,Manila,Filipinas,17171,12/10/2017 15:18,73618,1362,0.800000,0.02,176933,39.750000,0.28,1,39.750000,38.959999,10.910000,Southeast Asia,Capital Nacional,PENDING_PAYMENT,1362,75,http://images.acmesports.sports/Fighting+video...,Fighting video games,39.750000,0,12/14/2017 15:18,Standard Class
82511,DEBIT,4,4,59.990002,299.959992,Shipping on time,0,63,Children's Clothing,CA,EE. UU.,XXXXXXXXX,Zena,14046,Elliott,XXXXXXXXX,Consumer,91732,El Monte,NaN,4,Apparel,34.071892,-118.013886,Europe,Sheffield,Reino Unido,14046,10/26/2017 0:29,70493,1350,57.139999,0.16,173808,357.100006,0.20,1,357.100006,299.959992,59.990002,Northern Europe,Inglaterra,COMPLETE,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,10/30/2017 0:29,Standard Class

As seen on the table above, there seems to be some mismatch values, as an example: `Customer State` but it is an integer instead of string.

Let see if it is true.

Try to find the `Customer Zipcode` with the value of `Customer State` from the table above (95758).

In [ ]:
df[df['Customer Zipcode'] == 95758]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
1755,TRANSFER,2,4,54.810001,189.000000,Advance shipping,0,24,Women's Apparel,Elk Grove,EE. UU.,XXXXXXXXX,Mary,2141,Le,XXXXXXXXX,Consumer,CA,3133 Rocky Campus,95758.0,5,Golf,38.415695,-121.418564,Europe,Carlisle,Reino Unido,2141,8/17/2017 1:38,65701,502,11.000000,0.06,164197,50.000000,0.29,4,200.000000,189.000000,54.810001,Northern Europe,Inglaterra,PROCESSING,502,24,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,8/19/2017 1:38,Standard Class
2806,DEBIT,4,4,5.240000,84.480003,Shipping on time,0,7,Hockey,Elk Grove,EE. UU.,XXXXXXXXX,Gerald,7651,Little,XXXXXXXXX,Consumer,CA,11 Velvet Goose Court,95758.0,2,Fitness,38.415695,-121.418564,Europe,Madrid,Espa√±a,7651,6/27/2015 16:23,12173,135,3.520000,0.04,30428,22.000000,0.06,4,88.000000,84.480003,5.240000,Southern Europe,Madrid,COMPLETE,135,7,http://images.acmesports.sports/Nike+Dri-FIT+C...,Nike Dri-FIT Crew Sock 6 Pack,22.000000,0,7/1/2015 16:23,Standard Class
4232,DEBIT,5,4,1.300000,32.599998,Late delivery,1,75,Video Games,Elk Grove,EE. UU.,XXXXXXXXX,Rosalyn,17212,Sykes,XXXXXXXXX,Corporate,CA,2476 Wishing Branch Ledge,95758.0,9,Discs Shop,38.408680,-121.479057,Pacific Asia,Tokio,Jap√≥n,17212,12/11/2017 5:40,73659,1362,7.160000,0.18,176974,39.750000,0.04,1,39.750000,32.599998,1.300000,Eastern Asia,Tokio,COMPLETE,1362,75,http://images.acmesports.sports/Fighting+video...,Fighting video games,39.750000,0,12/16/2017 5:40,Standard Class
10017,TRANSFER,6,4,70.550003,235.160004,Shipping canceled,0,17,Cleats,Elk Grove,EE. UU.,XXXXXXXXX,Eric,9899,Smith,XXXXXXXXX,Corporate,CA,4472 Tawny Jetty,95758.0,4,Apparel,38.415695,-121.418564,Europe,Bremen,Alemania,9899,8/28/2017 0:02,66450,365,4.800000,0.02,166114,59.990002,0.30,4,239.960007,235.160004,70.550003,Western Europe,Bremen,SUSPECTED_FRAUD,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,0,9/3/2017 0:02,Standard Class
17000,CASH,2,4,38.689999,106.589996,Advance shipping,0,18,Men's Footwear,Elk Grove,EE. UU.,XXXXXXXXX,Mary,9161,Smith,XXXXXXXXX,Consumer,CA,4096 Amber Bend,95758.0,4,Apparel,38.415695,-121.418564,Africa,Port Elizabeth,SudAfrica,9161,12/17/2016 16:09,49096,403,23.400000,0.18,122757,129.990005,0.36,1,129.990005,106.589996,38.689999,Southern Africa,Cabo Oriental,CLOSED,403,18,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,12/19/2016 16:09,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169529,TRANSFER,6,2,56.779999,118.290001,Late delivery,1,18,Men's Footwear,Elk Grove,EE. UU.,XXXXXXXXX,Johnny,5963,Smith,XXXXXXXXX,Home Office,CA,7111 Indian Island Glade,95758.0,4,Apparel,38.409073,-121.419586,USCA,Concord,Estados Unidos,5963,7/14/2016 5:52,38380,403,11.700000,0.09,95785,129.990005,0.48,1,129.990005,118.290001,56.779999,West of USA,California,PENDING,403,18,http://images.acmesports.sports/Nike+Men%27s+C...,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,0,7/20/2016 5:52,Second Class
169639,TRANSFER,6,2,-15.380000,57.599998,Late delivery,1,9,Cardio Equipment,Elk Grove,EE. UU.,XXXXXXXXX,Johnny,5963,Smith,XXXXXXXXX,Home Office,CA,7111 Indian Island Glade,95758.0,3,Footwear,38.409073,-121.419586,USCA,Concord,Estados Unidos,5963,7/14/2016 5:52,38380,172,2.400000,0.04,95784,30.000000,-0.27,2,60.000000,57.599998,-15.380000,West of USA,California,PENDING,172,9,http://images.acmesports.sports/Nike+Women%27s...,Nike Women's Tempo Shorts,30.000000,0,7/20/2016 5:52,Second Class
169835,TRANSFER,6,2,65.730003,199.169998,Late delivery,1,17,Cleats,Elk Grove,EE. UU.,XXXXXXXXX,Johnny,5963,Smith,XXXXXXXXX,Home Office,CA,7111 Indian Island Glade,95758.0,4,Apparel,38.409073,-121.419586,USCA,Concord,Estados Unidos,5963,7/14/2016 5:52,38380,365,40.790001,0.17,95786,59.990002,0.33,4,239.960007,199.169998,65.730003,West of USA,California,PENDING,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,0,7/20/2016 5:52,Second Class
169839,TRANSFER,6,2,45.000000,150.000000,Late delivery,1,24,Women's Apparel,Elk Grove,EE. UU.,XXXXXXXXX,Johnny,5963,Smith,XXXXXXXXX,Home Office,CA,7111 Indian Island Glade,95758.0,5,Golf,38.409073,-121.419586,USCA,Concord,Estados Unidos,5963,7/14/2016 5:52,38380,502,50.000000,0.25,95787,50.000000,0.30,4,200.000000,150.000000,45.000000,West of USA,California,PENDING,502,24,http://images.acmesports.sports/Nike+Men%27s+D...,Nike Men's Dri-FIT Victory Golf Polo,50.000000,0,7/20/2016 5:52,Second Class
172121,TRANSFER,3,4,-2.290000,175.960007,Advance shipping,0,29,Shop By Sport,Elk Grove,EE. UU.,XXXXXXXXX,Richard,5575,Smith,XXXXXXXXX,Home Office,CA,7855 Golden Lake Limits,95758.0,5,Golf,38.415695,-121.418564,Europe,Quimper,Francia,5575,7/3/2017 22:11,62677,627,23.990000,0.12,156704,39.990002,-0.01,5,199.949997,175.960007,-2.290000,Western Europe,Breta√±a,PROCESSING,627,29,http://images.acmesports.sports/Under+Armour+G...,Under Armour Girls' Toddler Spine Surge Runni,39.990002,0,7/6/2017 22:11,Standard Class

Based on the result, not only for `Customer Zipcode`, but `Customer State`, `Customer City`, `Customer Street` are all in wrong places.

Change all those columns into the correct values, except for `Customer Street` because there is no reference and it is still logical to be in the same city as `Customer City`.

There is also no other data for these customers.

In [ ]:
df[(df['Customer Lname'] == 'Elliott') & (df['Customer Fname'] == 'Zena')]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
82511,DEBIT,4,4,59.990002,299.959992,Shipping on time,0,63,Children's Clothing,CA,EE. UU.,XXXXXXXXX,Zena,14046,Elliott,XXXXXXXXX,Consumer,91732,El Monte,NaN,4,Apparel,34.071892,-118.013886,Europe,Sheffield,Reino Unido,14046,10/26/2017 0:29,70493,1350,57.139999,0.16,173808,357.100006,0.2,1,357.100006,299.959992,59.990002,Northern Europe,Inglaterra,COMPLETE,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,10/30/2017 0:29,Standard Class

Replacing the values.

In [ ]:
df.loc[35704, ['Customer Zipcode', 'Customer State', 'Customer City']] = [95758, 'CA', 'Elk Grove']
df.loc[46440, ['Customer Zipcode', 'Customer State', 'Customer City']] = [95758, 'CA','Elk Grove']
df.iloc[[35704, 46440]]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
35704,DEBIT,2,1,66.379997,189.660004,Late delivery,1,65,Consumer Electronics,Elk Grove,EE. UU.,XXXXXXXXX,Sara,14577,Foreman,XXXXXXXXX,Consumer,CA,Elk Grove,95758.0,10,Technology,39.134159,-123.718552,Europe,Valence,Francia,14577,11/2/2017 18:31,71024,1352,63.220001,0.25,174339,252.880005,0.35,1,252.880005,189.660004,66.379997,Western Europe,Auvernia-R√≥dano-Alpes,COMPLETE,1352,65,http://images.acmesports.sports/Industrial+con...,Industrial consumer electronics,252.880005,0,11/4/2017 18:31,First Class
46440,PAYMENT,4,4,10.910000,38.959999,Shipping on time,0,75,Video Games,Elk Grove,EE. UU.,XXXXXXXXX,Eugenia,17171,Slater,XXXXXXXXX,Corporate,CA,Elk Grove,95758.0,9,Discs Shop,38.408573,-121.449112,Pacific Asia,Manila,Filipinas,17171,12/10/2017 15:18,73618,1362,0.800000,0.02,176933,39.750000,0.28,1,39.750000,38.959999,10.910000,Southeast Asia,Capital Nacional,PENDING_PAYMENT,1362,75,http://images.acmesports.sports/Fighting+video...,Fighting video games,39.750000,0,12/14/2017 15:18,Standard Class

In [ ]:
df[df['Customer Zipcode'] == 91732]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
1738,TRANSFER,4,4,-13.630000,191.970001,Shipping on time,0,17,Cleats,El Monte,EE. UU.,XXXXXXXXX,Cheryl,7457,Smith,XXXXXXXXX,Consumer,CA,2845 Jagged Oak Vale,91732.0,4,Apparel,34.194382,-118.166298,Europe,Sandnes,Noruega,7457,6/18/2015 16:55,11558,365,47.990002,0.20,28898,59.990002,-0.07,4,239.960007,191.970001,-13.630000,Northern Europe,Rogaland,PROCESSING,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,0,6/22/2015 16:55,Standard Class
1786,TRANSFER,4,4,24.590000,65.570000,Shipping on time,0,36,Golf Balls,El Monte,EE. UU.,XXXXXXXXX,Cheryl,7457,Smith,XXXXXXXXX,Consumer,CA,2845 Jagged Oak Vale,91732.0,6,Outdoors,34.194382,-118.166298,Europe,Sandnes,Noruega,7457,6/18/2015 16:55,11558,804,14.390000,0.18,28899,19.990000,0.38,4,79.959999,65.570000,24.590000,Northern Europe,Rogaland,PROCESSING,804,36,http://images.acmesports.sports/Glove+It+Women...,Glove It Women's Imperial Golf Glove,19.990000,0,6/22/2015 16:55,Standard Class
5637,TRANSFER,3,4,20.580000,49.000000,Advance shipping,0,7,Hockey,El Monte,EE. UU.,XXXXXXXXX,Cheryl,7457,Smith,XXXXXXXXX,Consumer,CA,2845 Jagged Oak Vale,91732.0,2,Fitness,34.194382,-118.166298,Europe,Odense,Dinamarca,7457,6/10/2015 21:08,11022,134,1.000000,0.02,27594,25.000000,0.42,2,50.000000,49.000000,20.580000,Northern Europe,Dinamarca Meridional,PROCESSING,134,7,http://images.acmesports.sports/Nike+Women%27s...,Nike Women's Legend V-Neck T-Shirt,25.000000,0,6/13/2015 21:08,Standard Class
9199,DEBIT,4,4,117.430000,260.959992,Shipping on time,0,17,Cleats,El Monte,EE. UU.,XXXXXXXXX,Steven,2951,Maddox,XXXXXXXXX,Consumer,CA,6724 High Chase,91732.0,4,Apparel,34.071892,-118.013886,Pacific Asia,Brisbane,Australia,2951,1/7/2016 2:27,25423,365,38.990002,0.13,63681,59.990002,0.45,5,299.950012,260.959992,117.430000,Oceania,Queensland,COMPLETE,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,0,1/11/2016 2:27,Standard Class
9525,DEBIT,5,4,7.600000,75.949997,Late delivery,1,41,Trade-In,El Monte,EE. UU.,XXXXXXXXX,Mary,5152,Andrews,XXXXXXXXX,Consumer,CA,436 Honey Willow Knoll,91732.0,6,Outdoors,34.094116,-118.095856,USCA,Tigard,Estados Unidos,5152,4/25/2016 17:53,32934,924,4.000000,0.05,82373,15.990000,0.10,5,79.949997,75.949997,7.600000,West of USA,Oreg√≥n,COMPLETE,924,41,http://images.acmesports.sports/Glove+It+Urban...,Glove It Urban Brick Golf Towel,15.990000,0,4/30/2016 17:53,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177719,TRANSFER,3,4,11.070000,40.980000,Advance shipping,0,46,Indoor/Outdoor Games,El Monte,EE. UU.,XXXXXXXXX,Cheryl,7457,Smith,XXXXXXXXX,Consumer,CA,2845 Jagged Oak Vale,91732.0,7,Fan Shop,34.194382,-118.166298,Europe,Odense,Dinamarca,7457,6/10/2015 21:08,11022,1014,9.000000,0.18,27595,49.980000,0.27,1,49.980000,40.980000,11.070000,Northern Europe,Dinamarca Meridional,PROCESSING,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,6/13/2015 21:08,Standard Class
178933,DEBIT,5,2,113.699997,227.410004,Late delivery,1,46,Indoor/Outdoor Games,El Monte,EE. UU.,XXXXXXXXX,Mary,1654,Smith,XXXXXXXXX,Corporate,CA,2916 Velvet Trace,91732.0,7,Fan Shop,34.071892,-118.013886,LATAM,Cuernavaca,M√©xico,1654,4/8/2015 6:20,6664,1014,22.490000,0.09,16646,49.980000,0.50,5,249.899994,227.410004,113.699997,Central America,Morelos,COMPLETE,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,4/13/2015 6:20,Second Class
178934,DEBIT,5,2,22.490000,224.910004,Late delivery,1,46,Indoor/Outdoor Games,El Monte,EE. UU.,XXXXXXXXX,Mary,1654,Smith,XXXXXXXXX,Corporate,CA,2916 Velvet Trace,91732.0,7,Fan Shop,34.071892,-118.013886,LATAM,Cuernavaca,M√©xico,1654,4/8/2015 6:20,6664,1014,24.990000,0.10,16645,49.980000,0.10,5,249.899994,224.910004,22.490000,Central America,Morelos,COMPLETE,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,4/13/2015 6:20,Second Class
178935,DEBIT,5,2,33.830002,179.929993,Late delivery,1,46,Indoor/Outdoor Games,El Monte,EE. UU.,XXXXXXXXX,Mary,1654,Smith,XXXXXXXXX,Corporate,CA,2916 Velvet Trace,91732.0,7,Fan Shop,34.071892,-118.013886,LATAM,Cuernavaca,M√©xico,1654,4/8/2015 6:20,6664,1014,19.990000,0.10,16644,49.980000,0.19,4,199.919998,179.929993,33.830002,Central America,Morelos,COMPLETE,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,4/13/2015 6:20,Second Class
180245,DEBIT,4,4,130.669998,395.980011,Shipping on time,0,45,Fishing,El Monte,EE. UU.,XXXXXXXXX,Mary,1610,Le,XXXXXXXXX,Corporate,CA,568 Broad Brook Common,91732.0,7,Fan Shop,32.801689,-116.978561,Pacific Asia,Yakarta,Indonesia,1610,1/30/2016 21:31,27053,1004,4.000000,0.01,67784,399.980011,0.33,1,399.980011,395.980011,130.669998,Southeast Asia,Yakarta,ON_HOLD,1004,45,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,2/3/2016 21:31,Standard Class

In [ ]:
df.loc[82511, ['Customer Zipcode', 'Customer State', 'Customer City']] = [91732, 'CA', 'El Monte']
df.iloc[[82511]]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
82511,DEBIT,4,4,59.990002,299.959992,Shipping on time,0,63,Children's Clothing,El Monte,EE. UU.,XXXXXXXXX,Zena,14046,Elliott,XXXXXXXXX,Consumer,CA,El Monte,91732.0,4,Apparel,34.071892,-118.013886,Europe,Sheffield,Reino Unido,14046,10/26/2017 0:29,70493,1350,57.139999,0.16,173808,357.100006,0.2,1,357.100006,299.959992,59.990002,Northern Europe,Inglaterra,COMPLETE,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,10/30/2017 0:29,Standard Class

Check the null-values in `Customer Lname` column.

In [ ]:
df[df['Customer Lname'].isnull()]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
41422,DEBIT,5,4,165.360001,337.459992,Late delivery,1,63,Children's Clothing,Caguas,Puerto Rico,XXXXXXXXX,May,17937,NaN,XXXXXXXXX,Corporate,PR,690 Cozy Meadow,725.0,4,Apparel,18.296438,-66.037048,Pacific Asia,Semarang,Indonesia,17937,12/21/2017 19:40,74384,1350,19.639999,0.06,177699,357.100006,0.49,1,357.100006,337.459992,165.360001,Southeast Asia,Java Central,COMPLETE,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,12/26/2017 19:40,Standard Class
50447,DEBIT,2,4,213.690002,436.100006,Advance shipping,0,66,Crafts,Palatine,EE. UU.,XXXXXXXXX,Contreras,14909,NaN,XXXXXXXXX,Corporate,IL,2407 Dusty Mount,60067.0,4,Apparel,42.110535,-88.102402,Europe,Estocolmo,Suecia,14909,11/7/2017 14:50,71356,1353,25.379999,0.06,174671,461.480011,0.49,1,461.480011,436.100006,213.690002,Northern Europe,Estocolmo,COMPLETE,1353,66,http://images.acmesports.sports/Porcelain+crafts,Porcelain crafts,461.480011,0,11/9/2017 14:50,Standard Class
86260,TRANSFER,5,4,152.440002,419.950012,Late delivery,1,66,Crafts,Los Angeles,EE. UU.,XXXXXXXXX,Ray,18347,NaN,XXXXXXXXX,Corporate,CA,131 Sunny Treasure Green,90027.0,4,Apparel,34.020344,-118.188965,Pacific Asia,Shenzhen,China,18347,12/27/2017 19:19,74794,1353,41.529999,0.09,178109,461.480011,0.36,1,461.480011,419.950012,152.440002,Eastern Asia,Guangdong,PENDING,1353,66,http://images.acmesports.sports/Porcelain+crafts,Porcelain crafts,461.480011,0,1/1/2018 19:19,Standard Class
92621,TRANSFER,2,1,-4.860000,194.240005,Late delivery,1,76,Women's Clothing,Caguas,Puerto Rico,XXXXXXXXX,BlueOneal,17354,NaN,XXXXXXXXX,Corporate,PR,9279 Quaking Key,725.0,4,Apparel,18.242476,-66.037064,Pacific Asia,Manila,Filipinas,17354,12/13/2017 7:25,73801,1363,21.580000,0.10,177116,215.820007,-0.03,1,215.820007,194.240005,-4.860000,Southeast Asia,Capital Nacional,PENDING,1363,76,http://images.acmesports.sports/Summer+dresses,Summer dresses,215.820007,0,12/15/2017 7:25,First Class
97530,DEBIT,4,2,82.540001,242.759995,Late delivery,1,65,Consumer Electronics,San Antonio,EE. UU.,XXXXXXXXX,York,14446,NaN,XXXXXXXXX,Home Office,TX,2905 Quaking Concession,78240.0,10,Technology,29.529984,-98.608292,Europe,Brescia,Italia,14446,10/31/2017 20:37,70893,1352,10.120000,0.04,174208,252.880005,0.34,1,252.880005,242.759995,82.540001,Southern Europe,Lombard√≠a,ON_HOLD,1352,65,http://images.acmesports.sports/Industrial+con...,Industrial consumer electronics,252.880005,0,11/4/2017 20:37,Second Class
120404,TRANSFER,3,4,157.830002,415.329987,Advance shipping,0,66,Crafts,Fayetteville,EE. UU.,XXXXXXXXX,Farley,14870,NaN,XXXXXXXXX,Consumer,NC,2544 Broad Brook View,28314.0,4,Apparel,35.062752,-79.005745,Europe,Cologne,Alemania,14870,11/7/2017 1:10,71317,1353,46.150002,0.10,174632,461.480011,0.38,1,461.480011,415.329987,157.830002,Western Europe,Renania del Norte-Westfalia,PENDING,1353,66,http://images.acmesports.sports/Porcelain+crafts,Porcelain crafts,461.480011,0,11/10/2017 1:10,Standard Class
166129,PAYMENT,2,2,-59.279999,296.390015,Shipping on time,0,63,Children's Clothing,Honolulu,EE. UU.,XXXXXXXXX,Le,17929,NaN,XXXXXXXXX,Home Office,HI,8547 Old Drive,96822.0,4,Apparel,21.287289,-157.671402,Pacific Asia,Surabaya,Indonesia,17929,12/21/2017 16:52,74376,1350,60.709999,0.17,177691,357.100006,-0.20,1,357.100006,296.390015,-59.279999,Southeast Asia,Java Oriental,PENDING_PAYMENT,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,12/23/2017 16:52,Second Class
167119,PAYMENT,2,4,15.050000,200.710007,Advance shipping,0,76,Women's Clothing,Reseda,EE. UU.,XXXXXXXXX,Huff,20439,NaN,XXXXXXXXX,Home Office,CA,7107 Blue Rise Place,91335.0,4,Apparel,34.199581,-118.536407,Pacific Asia,Agra,India,20439,1/27/2018 8:14,76886,1363,15.110000,0.07,180201,215.820007,0.08,1,215.820007,200.710007,15.050000,South Asia,Uttar Pradesh,PENDING_PAYMENT,1363,76,http://images.acmesports.sports/Summer+dresses,Summer dresses,215.820007,0,1/29/2018 8:14,Standard Class

In [ ]:
df["Customer Lname"].fillna(df["Customer Fname"], inplace = True)
df[df['Customer Lname'].isnull()]

Empty DataFrame
Columns: [Type, Days for shipping (real), Days for shipment (scheduled), Benefit per order, Sales per customer, Delivery Status, Late_delivery_risk, Category Id, Category Name, Customer City, Customer Country, Customer Email, Customer Fname, Customer Id, Customer Lname, Customer Password, Customer Segment, Customer State, Customer Street, Customer Zipcode, Department Id, Department Name, Latitude, Longitude, Market, Order City, Order Country, Order Customer Id, order date (DateOrders), Order Id, Order Item Cardprod Id, Order Item Discount, Order Item Discount Rate, Order Item Id, Order Item Product Price, Order Item Profit Ratio, Order Item Quantity, Sales, Order Item Total, Order Profit Per Order, Order Region, Order State, Order Status, Product Card Id, Product Category Id, Product Image, Product Name, Product Price, Product Status, shipping date (DateOrders), Shipping Mode]
Index: []

Re-check a column.

In [ ]:
df.iloc[[41422]]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
41422,DEBIT,5,4,165.360001,337.459992,Late delivery,1,63,Children's Clothing,Caguas,Puerto Rico,XXXXXXXXX,May,17937,May,XXXXXXXXX,Corporate,PR,690 Cozy Meadow,725.0,4,Apparel,18.296438,-66.037048,Pacific Asia,Semarang,Indonesia,17937,12/21/2017 19:40,74384,1350,19.639999,0.06,177699,357.100006,0.49,1,357.100006,337.459992,165.360001,Southeast Asia,Java Central,COMPLETE,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,12/26/2017 19:40,Standard Class

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180519 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180519 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Product Card Id                180519 non-null  int64
 44  Product Category Id            180519 non-null  int64
 45  Product Image                  180519 non-null  object
 46  Product Name                   180519 non-null  object
 47  Product Price                  180519 non-null  float64
 48  Product Status                 180519 non-null  int64
 49  shipping date (DateOrders)     180519 non-null  object
 50  Shipping Mode                  180519 non-null  object
dtypes: float64(13), int64(14), object(24)
memory usage: 70.2+ MB

There is no null-values.

##Checking Duplicates

In [ ]:
df.duplicated().sum()

0

There is no duplicated values.

##Saving the Dataframe

Saving the dataframe into csv files to be visualized using Tableau.

In [ ]:
df.to_csv('Supply_Chain_Dataset_Clean.csv', sep=',', index=False, encoding='utf-8')